<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LosBase\Controller\AbstractCrudController'    => __DIR__ . '/src/LosBase/Controller/AbstractCrudController.php',
  'LosBase\Controller\AbstractCrudImgController' => __DIR__ . '/src/LosBase/Controller/AbstractCrudImgController.php',
  'LosBase\Controller\EntityManagerAware'        => __DIR__ . '/src/LosBase/Controller/EntityManagerAware.php',
  'LosBase\Entity\AbstractEntity'                => __DIR__ . '/src/LosBase/Entity/AbstractEntity.php',
  'LosBase\EventManager\EventProvider'           => __DIR__ . '/src/LosBase/EventManager/EventProvider.php',
  'LosBase\Form\AbstractForm'                    => __DIR__ . '/src/LosBase/Form/AbstractForm.php',
  'LosBase\InputFilter\Factory'                  => __DIR__ . '/src/LosBase/InputFilter/Factory.php',
  'LosBase\Module'                               => __DIR__ . '/src/LosBase/Module.php',
  'LosBase\Service\AbstractEntity'               => __DIR__ . '/src/LosBase/Service/AbstractEntity.php',
  'LosBase\Service\Util'                         => __DIR__ . '/src/LosBase/Service/Util.php',
  'LosBase\Singleton'                            => __DIR__ . '/src/LosBase/Singleton.php',
  'LosBase\Validator\NoEntityExists'             => __DIR__ . '/src/LosBase/Validator/NoEntityExists.php',
  'LosBase\Validator\NoOtherEntityExists'        => __DIR__ . '/src/LosBase/Validator/NoOtherEntityExists.php',
  'LosBase\Version'                              => __DIR__ . '/src/LosBase/Version.php',
  'LosBase\View\Helper\Version'                  => __DIR__ . '/src/LosBase/View/Helper/Version.php',
);
